server:
  port: 8027


spring:
  application:
    name: MultiWatch

  datasource:
    url: jdbc:mysql://localhost:3308/multi_watch
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: monitoring-reading-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.monitoring.infrastructure.kafka.message"